// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hcxcdubmcvrdepcopkct.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhjeGNkdWJtY3ZyZGVwY29wa2N0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MTQ0NTMsImV4cCI6MjA3Mzk5MDQ1M30.dde2f38DrKbi3dZFFOVx1aTuGbrBClcJ9Rud-g9P-3Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});